CREATE TABLE public.users (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	email varchar(255) NOT NULL,
	hashed_password varchar(255) NOT NULL,
	"role" varchar(20) NOT NULL,
	"name" varchar(50) DEFAULT ''::character varying NOT NULL,
	phone_number varchar(15) NOT NULL,
	CONSTRAINT users_pk PRIMARY KEY (id),
	CONSTRAINT users_unique UNIQUE (email)
);

INSERT INTO public.users (email, hashed_password, "role", "name", phone_number) VALUES('admin', '$2b$12$dQ7BJ6YcMoN9DOGL.W8oF.hd2NTEKUIlPN5OxIIKhZYu4cHtrkLka', 'admin', 'Админ', ''); -- пароль 123
INSERT INTO public.users (email, hashed_password, "role", "name", phone_number) VALUES('user', '$2b$12$J3ICx1iMw51B8SvC3xhGeOPSV5zhrfbLWTBwcndCzTL.bLk3y9Ww.', 'user', 'Пользователь', ''); -- user
INSERT INTO public.users (email, hashed_password, "role", "name", phone_number) VALUES('company', '$2b$12$nPn38YTJFjOItVlyw6ylp.24hlmv.9eC/PnrZs2Gt19bOJecY2AM.', 'company', 'Владелец организации', ''); -- company
INSERT INTO public.users (email, hashed_password, "role", "name", phone_number) VALUES('another_user', '$2b$12$qwjVq/nyAcTx6p0.8vzxW.1kBYxs.elPRu6DkNWg.hIfZTah5EqRS', 'user', 'Другая огранизация', ''); -- another_user

CREATE TABLE public.companies (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" varchar(255) NOT NULL,
	rating float8 DEFAULT 0 NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT companies_pk PRIMARY KEY (id),
	CONSTRAINT companies_users_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

ALTER TABLE public.companies ALTER COLUMN rating TYPE numeric(4, 2) USING rating::numeric(4, 2);

ALTER TABLE public.companies ADD email varchar(255) NOT NULL;
ALTER TABLE public.companies ADD inn varchar(12) NOT NULL;
ALTER TABLE public.companies ADD phone_number varchar(15) NOT NULL;
ALTER TABLE public.companies ADD staff int8 NOT NULL;
ALTER TABLE public.companies ADD description text NOT NULL;
ALTER TABLE public.companies ADD site varchar(255) NOT NULL;

ALTER TABLE public.companies ADD CONSTRAINT companies_unique UNIQUE (user_id,"name");

CREATE TABLE public.services (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" varchar(255) NOT NULL,
	price numeric(15, 2) NOT NULL,
	company_id int8 NOT NULL,
	CONSTRAINT services_pk PRIMARY KEY (id),
	CONSTRAINT services_unique UNIQUE (company_id,"name"),
	CONSTRAINT services_companies_fk FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE
);

CREATE TABLE public.projects (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" varchar(255) NOT NULL,
	description text NULL,
	company_id int8 NOT NULL,
	CONSTRAINT projects_pk PRIMARY KEY (id),
	CONSTRAINT projects_unique UNIQUE (company_id,"name"),
	CONSTRAINT projects_companies_fk FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE
);

CREATE TABLE public.reviews (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"content" text NOT NULL,
	rating int8 NOT NULL,
	company_id int8 NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT reviews_pk PRIMARY KEY (id),
	CONSTRAINT reviews_unique UNIQUE (user_id,company_id),
	CONSTRAINT reviews_users_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE,
	CONSTRAINT reviews_companies_fk FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE
);